# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
 
trigger:
- test-deployment
 
pool:
  vmImage: ubuntu-latest

# Set variables
variables:
  stage: development
  serviceConnection: scalework_sc
  appServiceName: scalework
 
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: use Node $(versionSpec)
 
- script: |
    npm install
    npm run build
  workingDirectory: $(Build.SourcesDirectory)
  displayName: 'install and build'
 
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: $(Build.SourcesDirectory)
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true
 
- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  displayName: 'Upload package'
  artifact: drop
 
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'scalework_sc'
    appType: 'webAppLinux'
    WebAppName: 'scalework'
    packageForLinux: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip